[package]
name = "artifact_serde"
version = "0.1.0"
authors = ["Alec Goncharow <Alec.Goncharow@gmail.com>"]

[dependencies]
base64 = "*"
regex = "*"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
